### ISSUE TITLE
APIError 9003 on server.py

### ISSUE THREAD

**Issue by pifou25** [pifou25/wideq#1]
the login / token works fine, but have an error from the API when I try the "ls" command. Same action works with the existing example.py but I could'nt see the difference.

state is almost ok, only missing the "session" but it doesn't refresh as expected...

here is the traceback:

127.0.0.1 - - [10/Apr/2020 22:48:06] "GET /ls HTTP/1.1" 301 -
[2020-04-10 22:48:07,223] ERROR in app: Exception on /ls/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 122, in get_ls
    for device in client.devices:
  File "/home/pi/Documents/wideq/wideq/client.py", line 126, in devices
    self._devices = self.session.get_devices()
  File "/home/pi/Documents/wideq/wideq/client.py", line 117, in session
    self._session, self._devices = self.auth.start_session()
  File "/home/pi/Documents/wideq/wideq/core.py", line 336, in start_session
    self.gateway.country, self.gateway.language)
  File "/home/pi/Documents/wideq/wideq/core.py", line 233, in login
    return lgedm_post(url, data)
  File "/home/pi/Documents/wideq/wideq/core.py", line 188, in lgedm_post
    raise APIError(code, message)
wideq.core.APIError: (9003, '세션생성실패')
127.0.0.1 - - [10/Apr/2020 22:48:07] "GET /ls/ HTTP/1.1" 500 -

**Comment by pifou25** [comment]
using google translate: 세션생성실패 = "session creation failure" :'(

**Comment by pifou25** [comment]
close while added a new APIError code 9003 for catching this error as a 'not logged' error
